import matplotlib.pyplot as plt
import pandas as pd


c = pd.read_csv('cycliclr.csv')
l = pd.read_csv('linearlr.csv')
s = pd.read_csv('steplr.csv')
cos = pd.read_csv('cosineannealinglr.csv')
epochs = [i for i in range(1, 51)]
fig=plt.figure(figsize=(24,24))
plt.subplot(2,2,1)
plt.yticks([10, 50, 70, 80, 85, 90, 95], fontsize=30)
plt.ylim(0, 100)
plt.plot(epochs, c.train, 'r', label="CyclicLR train",linewidth=5)
plt.plot(epochs, c.valid, 'r', linestyle='--', label="CyclicLR validation",linewidth=5)
plt.xlabel('Epochs',fontsize=30)
plt.ylabel('%',fontsize=30)
plt.legend(fontsize=30)
plt.subplot(2,2,2)
plt.yticks([10, 50, 70, 80, 85, 90, 95], fontsize=30)
plt.ylim(0, 100)
plt.plot(epochs, s.train, 'm', label="StepLR train",linewidth=5)
plt.plot(epochs, s.valid, 'm', linestyle='--', label="StepLR validation",linewidth=5)
plt.xlabel('Epochs',fontsize=30)
plt.ylabel('%',fontsize=30)
plt.legend(fontsize=30)
plt.subplot(2,2,3)
plt.yticks([10, 50, 70, 80, 85, 90, 95], fontsize=30)
plt.ylim(0, 100)
plt.plot(epochs, l.train, 'g', label="LinearLR train",linewidth=5)
plt.plot(epochs, l.valid, 'g',linestyle='--', label="LinearLR validation",linewidth=5)
plt.xlabel('Epochs',fontsize=30)
plt.ylabel('%',fontsize=30)
plt.legend(fontsize=30)
plt.subplot(2,2,4)
plt.yticks([10, 50, 70, 80, 85, 90, 95], fontsize=30)
plt.ylim(0, 100)
plt.plot(epochs, cos.train, 'c', label="CosineAnnealingLR train",linewidth=5)
plt.plot(epochs, cos.valid, 'c',linestyle='--', label="CosineAnnealingLR validation",linewidth=5)
plt.xlabel('Epochs',fontsize=30)
plt.ylabel('%',fontsize=30)
plt.legend(fontsize=30)

fig.suptitle("Accuracy progress of train/validation for 4 LR schedulers",y=0.92,fontsize=45)
plt.savefig('sched.pdf', format='pdf', bbox_inches='tight')